[theme]
base="light"
primaryColor="#F6DA7A"
backgroundColor="#FFF9E6"
secondaryBackgroundColor="#FFF0F5"
textColor="#111827"
font="sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false